# Practice Numpy

**Kusoft Machine Learning team first assignment.**

Subject: Numpy<br>
Deadline: Friday, Feb 3, 11:59 PM

After downloading this notebook, work on the exercises bellow, and submit your solution before the deadline.<br>
To clone the whole repository in your local machine, you can run the command bellow in your command line; please note than you must have *Git* installed in your machine in order for the command bellow to run successfully. Or you can download it using *Github Ui*.<br>
`git clone https://github.com/hikmatullah-mohammadi/kusoft-ml-team-assignments`

In [1]:
# import 'numpy'
import numpy as np

# 1- Data

Let's creat an array called *data*. The ***data*** array has a shape of (99, 9). Each column is comprised of 99 multiples of the corresponding headers i.e. 1, 2, 3, 4, 5, 6, 7, 8, 9. In other words, column 1 is comprised of 99 multiples of 1, etc.

In [2]:
# create a dataset
col_1 = np.arange(1, 100)
col_2 = np.arange(2, 200, 2)
col_3 = np.arange(3, 300, 3)
col_4 = np.arange(4, 400, 4)
col_5 = np.arange(5, 500, 5)
col_6 = np.arange(6, 600, 6)
col_7 = np.arange(7, 700, 7)
col_8 = np.arange(8, 800, 8)
col_9 = np.arange(9, 900, 9)

data = np.array([col_1, col_2, col_3, col_4, col_5, col_6, col_7, col_8, col_9]).T
data.shape

(99, 9)

In [3]:
data[:10]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81],
       [10, 20, 30, 40, 50, 60, 70, 80, 90]])

# 2- Exercises

#### 1)

Cosider *data* array and write Python code to extract and display only those **rows** with an index of **odd**. [HINT: use slicing].<br>
**Example output:**
```
array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99],
       ...
```

#### 2)

Considering the above mentioned array, *data*, write the python code to display only those **columns** of which headers are **even** numbers. [HINT: use slicing] <br>
**Example output:**
```
array([[  2,   4,   6,   8],
       [  4,   8,  12,  16],
       [  6,  12,  18,  24],
       [  8,  16,  24,  32],
       [ 10,  20,  30,  40],
       ...           
```

#### 3)

In *data* array, first extract the column with an index of **2**, which consists of multiples of **3**. Then display those numbers in this column which are multiples of **9** as well. [HINT: use slicing & '%' sign].<br>
**Output:**
```
array([  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108, 117,
       126, 135, 144, 153, 162, 171, 180, 189, 198, 207, 216, 225, 234,
       243, 252, 261, 270, 279, 288, 297])
```

#### 4)

Find the **index** of every row of which mean is a multiple of **3** (`x%3==0`). [HINT: use where() and mean() methods]. <br>
Remember! You can find the mean of every row using this code snippet, `data.mean(axis=1)`.<br>
**Output:**
```
(array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
        53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98],
       dtype=int64),)
```
**Explanations:**<br>
The mean of these rows are multiples of **3**.

#### 5) 

Consider the *data* array, and write the Python code to display the **index** of those **columns** of which **sums** are less than **20000**.<br>
[HINT: You can use `data.sum(axis=0)` to find the sum of all columns.]<br>
**Output:**
```
(array([0, 1, 2, 3], dtype=int64),)
```
**Explanations:**<br>
The sums of columns with indices 0, 1, 2 and 3 are less than 20000.


# Thanks:)